// CosmicMode — the cosmic web, the first thing the player sees. OWNED BY THE COSMIC TRACK.
//
//   Physics   Gaussian random field with an EH98 ΛCDM spectrum (σ8-normalised) generated by a real 3D
//             FFT in a Web Worker (ic.worker.js) → Zel'dovich + 2LPT displacements → GPU particle-mesh
//             gravity with COLA time stepping (sim.js). Comoving box, flat ΛCDM a(t), growth D1/D2.
//   Look      projected column density of 0.26–2.1 M particles with adaptive smoothing, TNG-style
//             temperature colouring, galaxies igniting on their host particles (render.js).
//   Opening   z = 49 fog → sheets → filaments → nodes over ~32 s, then slow future evolution forever;
//             expansion is shown by the comoving camera distance shrinking as a(t) grows.
//
// Units: 1 world unit = 1 comoving Mpc/h. The box is L = 256 Mpc/h, periodic; rendering wraps it around
// the camera so it tiles an infinite universe. Sim time τ (s) → a(τ) via the growth factor.
//
// Contract: clicking/tapping a galaxy or cluster flies to it, then
//   engine.director.go('galaxy', { galaxy: <index> }, { transition: 'fade' })
//
// URL extras (all optional): ct=<sec> start the opening timeline at τ (40 = mature web today),
//   cl=<rank> orbit cluster #rank (0 = most massive), dist=<Mpc/h>, yaw/pitch=<deg>, gal=<rank> frame a galaxy.
import * as THREE from 'three';
import { Mode } from '../../core/Mode.js';
import { OrbitRig } from '../../core/OrbitRig.js';
import { D1, D2, ageGyr, driftFactor, formatAge, formatZ, zOfA } from './cosmology.js';
import { CosmicSim, atlasTiles } from './sim.js';
import { CosmicRenderer } from './render.js';
import { clusterNames } from './names.js';

const BOX = 256;            // Mpc/h
const A_START = 1 / 50;     // z = 49
const T_OPEN = 32;          // s, opening sequence length (z = 49 → 0)
const A_PM0 = 0.05;         // COLA starts at z = 19 (2LPT is exact enough before)
const DA = 0.04;            // PM step in a
const DS_SAT = 0.5;         // saturation of the sub-mesh Zel'dovich growth (truncated ZA)
const DEG = Math.PI / 180;

const LN_DS = Math.log(D1(A_START));
function aOfD(D) {
  let lo = Math.log(1e-3), hi = Math.log(3);
  for (let k = 0; k < 40; k++) { const m = 0.5 * (lo + hi); if (D1(Math.exp(m)) < D) lo = m; else hi = m; }
  return Math.exp(0.5 * (lo + hi));
}
/** Scale factor along the opening timeline. Growth is eased so the web emerges ~10 s in and matures by ~26 s. */
function aAt(tau) {
  if (tau <= 0) return A_START;
  if (tau < T_OPEN) {
    const u = tau / T_OPEN;
    const w = 1 - Math.pow(1 - u, 1.6);
    return aOfD(Math.exp(LN_DS * (1 - w)));
  }
  return 1 + 0.55 * (1 - Math.exp(-(tau - T_OPEN) / 420));   // the future: slow Λ-dominated growth
}
const subGrowth = (a) => { const d = D1(a); return d / Math.sqrt(1 + (d / DS_SAT) * (d / DS_SAT)); };
/** Visual expansion: the comoving camera distance shrinks as (a/1)^0.32 while the opening plays. */
const sVis = (a) => Math.pow(Math.min(a, 1.2), 0.32);

function h32(x) { x |= 0; x ^= x >>> 16; x = Math.imul(x, 0x7feb352d); x ^= x >>> 15; x = Math.imul(x, 0x846ca68b); x ^= x >>> 16; return x >>> 0; }

export default class CosmicMode extends Mode {
  constructor(engine) {
    super(engine);
    this.inputScheme = 'orbit';
    this.look = {
      exposure: 1.0, tonemap: 'agx',
      bloom: { strength: 0.75, radius: 0.8, threshold: 0.9, knee: 0.7 },
      vignette: 0.32, grain: 0.012, chromatic: 0.0008, saturation: 1.12, contrast: 1.06, blackPoint: 0.0,
    };
    this.icStage = 0;
    this.tau = 0;
    this.a = A_START;
    this.disposed = false;
    this._v3 = new THREE.Vector3(); this._v3b = new THREE.Vector3(); this._v3c = new THREE.Vector3();
    this._fwd = new THREE.Vector3();
    this.camC = new THREE.Vector3();
    this.clusterPos = null; this.galPos = null;
    this.hover = null;
    this.pending = null;       // fly-to then dive
    this._frame = 0;
    this._teleT = 0;
    this._ringA = 0;
  }

  // ------------------------------------------------------------------ lifecycle
  async enter(params = {}) {
    const e = this.engine;
    const q = e.quality;
    const raw = e.params.raw;
    const tier = q.tier || 'high';
    this.params = params;
    const num = (k) => { const v = raw?.get?.(k); if (v === null || v === undefined || v === '') return undefined; const f = parseFloat(v); return Number.isFinite(f) ? f : undefined; };
    const N = tier === 'low' ? 64 : 128;
    const M = num('mesh') ?? N;             // PM mesh = particle lattice (COLA needs force resolution ≥ lattice)
    const K = num('k') ?? (tier === 'low' ? 2 : tier === 'med' ? 1 : tier === 'ultra' ? 4 : 3);
    this.cfg = {
      N, M, K, drawCount: N * N * N,
      h0: (BOX / N) * 0.8,
      maxPx: tier === 'low' ? 10 : tier === 'med' ? 14 : tier === 'ultra' ? 24 : 18,
      accumScale: tier === 'low' ? 0.6 : 1,
      galaxyMax: tier === 'low' ? 9000 : tier === 'med' ? 18000 : tier === 'ultra' ? 48000 : 30000,
    };
    this.startTau = params.returning ? T_OPEN + 6 : (num('ct') ?? params.ct ?? 0);
    this.focusCluster = Math.max(0, Math.floor(num('cl') ?? 0));
    this.focusGalaxy = num('gal');

    // --- GPU sim + renderer
    this.sim = new CosmicSim(e.renderer, { N, M, sub: subGrowth });
    if (num('pm') === 0) this.sim.ok = false;
    this.view = new CosmicRenderer(e, this.sim, { L: BOX, K, drawCount: this.cfg.drawCount, h0: this.cfg.h0, maxPx: this.cfg.maxPx, accumScale: this.cfg.accumScale, fog: 60 });
    this.scene.add(this.view.comp);
    // look tuning (URL overrides are for art-direction iteration)
    const cu0 = this.view.compMat.uniforms, au0 = this.view.accMat.uniforms;
    cu0.uSigma0.value = num('s0') ?? cu0.uSigma0.value;
    cu0.uGain.value = num('gain') ?? cu0.uGain.value;
    cu0.uHeatGain.value = num('heat') ?? cu0.uHeatGain.value;
    this.view.U.uFog.value = num('fog') ?? this.view.U.uFog.value;
    au0.uH0.value *= num('h0') ?? 1;
    au0.uHeatLo.value = num('hlo') ?? au0.uHeatLo.value; au0.uHeatHi.value = num('hhi') ?? au0.uHeatHi.value;
    this.cocK = num('coc') ?? 1.2;
    this.scene.add(this.view.ring);
    this.scene.background = new THREE.Color(0x000000);
    this._syncSize();

    // --- camera: a proxy rig in comoving coordinates; the real camera stays at the origin
    this.camera.fov = 55; this.camera.near = 0.01; this.camera.far = 2000; this.camera.updateProjectionMatrix();
    this.rigCam = new THREE.PerspectiveCamera(55, e.aspect, 0.01, 2000);
    const r0 = new OrbitRig(this.rigCam, {
      distance: num('dist') ?? 62, minDistance: 1.5, maxDistance: 420,
      yaw: (num('yaw') ?? 38) * DEG, pitch: (num('pitch') ?? 16) * DEG, idleDrift: 0.012, smooth: 4, panSpeed: 0.6,
    });
    this.rig = r0;

    // --- initial conditions (worker)
    this._startWorker();

    e.ui?.setLocation?.({ scale: 'Universe', title: 'Cosmic Web', subtitle: `${BOX} Mpc/h · ΛCDM` });
    if (!params.returning) e.ui?.showTitle?.('REVERENCE', 'a universe, alive', 5200);
    e.ui?.hint?.('drag to orbit · scroll or pinch to zoom · WASD to drift · tap a cluster to descend', 9000);
    e.audio?.setScene?.('cosmic');
  }

  _startWorker() {
    const e = this.engine;
    let w;
    try {
      w = new Worker(new URL('./ic.worker.js', import.meta.url), { type: 'module' });
    } catch (err) {
      console.error('[cosmic] worker failed', err);
      this.icStage = -1; this.ready = true; return;
    }
    this.worker = w;
    const { N, M } = this.cfg;
    const tilesX = atlasTiles(N);
    w.onmessage = (ev) => { try { this._onWorker(ev.data); } catch (err) { console.error('[cosmic] IC upload failed', err); this.icStage = -1; this.ready = true; } };
    w.onerror = (err) => { console.error('[cosmic] IC worker error', err.message || err); this.icStage = -1; this.ready = true; };
    w.postMessage({
      cmd: 'ic', seed: e.universe.seed >>> 0, N, M, box: BOX, tilesX,
      galaxyMax: this.cfg.galaxyMax, clusterMax: 160, clusterSep: 16, rGlow: 7, rGal: 1.6, rCluster: 5, rEnv: 9,
    });
  }

  _tex(data) {
    const s = this.sim;
    const t = new THREE.DataTexture(data, s.W, s.H, THREE.RGBAFormat, THREE.FloatType);
    t.minFilter = t.magFilter = THREE.NearestFilter; t.generateMipmaps = false; t.needsUpdate = true;
    (this._texs ||= []).push(t);
    return t;
  }

  _onWorker(msg) {
    if (this.disposed) return;
    if (msg.type === 'error') { console.error('[cosmic] IC worker:', msg.error); this.icStage = -1; this.ready = true; return; }
    if (msg.type === 'stage1') {
      this.atlasA = msg.atlasA;
      this.sim.setIC({ psiA: this._tex(msg.atlasA) });
      this.view.U.uSigGlow.value = msg.sigGlow;
      this.icStage = 1;
      if (this.engine.params.debug) console.log(`[cosmic] stage1 ${msg.ms.toFixed(0)} ms`);
    } else if (msg.type === 'stage2') {
      this.atlasB = msg.atlasB;
      this.sim.setIC({ psiB: this._tex(msg.atlasB), psiS: msg.atlasS ? this._tex(msg.atlasS) : null });
      this._setupCatalog(msg.galaxies, msg.clusters);
      this.icStage = 2;
      if (this.engine.params.debug) console.log(`[cosmic] stage2 ${msg.stats.ms.toFixed(0)} ms`, msg.stats, msg.galaxies.count, msg.clusters.count);
      this.worker?.terminate(); this.worker = null;
      // jump along the timeline (URL ct / returning): the sim catches up in update()
      if (this.startTau > 0) { this.tau = this.startTau; this.tauJumped = true; }
      this._frameInitialCamera();
    }
  }

  _setupCatalog(gal, cl) {
    const e = this.engine;
    const count = e.universe.cosmic?.galaxyCount ?? 4096;
    this.gal = gal; this.cl = cl;
    // universe galaxy index per catalog entry (catalog is sorted brightest centrals first)
    const G = gal.count;
    this.galIndex = new Int32Array(G);
    const morph = new Float32Array(G);
    for (let i = 0; i < G; i++) {
      const idx = i < count ? i : h32(e.universe.seed * 31 + i) % count;
      this.galIndex[i] = idx;
      const kind = gal.kind[i];
      let m;
      if (i < count) {
        const t = e.universe.galaxy(idx)?.type;
        m = t === 'elliptical' || t === 'lenticular' ? 0 : t === 'irregular' ? 2 : 1;
      } else m = kind === 2 ? ((h32(i) & 3) === 0 ? 2 : 1) : (kind === 1 && (h32(i + 7) & 1) ? 0 : 1);
      morph[i] = m;
    }
    const pts = this.view.setGalaxies(gal, morph);
    this.scene.add(pts);
    // cluster membership counts + names
    const members = new Int32Array(cl.count);
    for (let i = 0; i < G; i++) if (gal.cluster[i] >= 0) members[gal.cluster[i]]++;
    this.clMembers = members;
    this.clNames = clusterNames(e.universe.seed, cl.count);
    // gather list: cluster cores, then the brightest galaxies (picking + markers)
    const list = [];
    for (let k = 0; k < cl.count; k++) list.push({ id: cl.center[k], mode: 1 });
    this.galGatherStart = list.length;
    const nG = Math.min(G, 64 * 64 - list.length);
    const byLum = Array.from({ length: G }, (_, i) => i).sort((x, y) => gal.lum[y] - gal.lum[x]).slice(0, nG);
    this.galGather = Int32Array.from(byLum);
    for (const i of byLum) list.push({ id: gal.host[i], mode: 0 });
    this.view.setGatherList(list);
  }

  /** Lagrangian (2LPT, a = 1) estimate of where a lattice particle ends up — used before the GPU gather arrives. */
  _lptPos(id, out) {
    const N = this.cfg.N, tx = atlasTiles(N), W = tx * N;
    const x = id % N, y = Math.floor(id / N) % N, z = Math.floor(id / (N * N));
    const t = ((y + Math.floor(z / tx) * N) * W + x + (z % tx) * N) * 4;
    const A = this.atlasA, B = this.atlasB, d2 = D2(1);
    out.set((x + 0.5) / N, (y + 0.5) / N, (z + 0.5) / N);
    if (A) out.x += A[t], out.y += A[t + 1], out.z += A[t + 2];
    if (B) out.x += d2 * B[t], out.y += d2 * B[t + 1], out.z += d2 * B[t + 2];
    return out;
  }

  _frameInitialCamera() {
    const cl = this.cl;
    let p = new THREE.Vector3(0.5, 0.5, 0.5);
    if (this.focusGalaxy !== undefined && this.gal?.count) {
      const gi = this.galGather?.[Math.min(this.galGather.length - 1, Math.max(0, Math.floor(this.focusGalaxy)))] ?? 0;
      this._lptPos(this.gal.host[gi], p);
      this.rig.distance = this.rig._dist = Math.min(this.rig.distance, 10);
    } else if (cl?.count) this._lptPos(cl.center[Math.min(cl.count - 1, this.focusCluster)], p);
    p.multiplyScalar(BOX);
    this.rig.target.copy(p); this.rig._target.copy(p);
  }

  exit() {
    this.disposed = true;
    try { this.worker?.terminate(); } catch (_) { /* ignore */ }
    this.engine.ui?.setMarkers?.([]);
    this.engine.ui?.setTelemetry?.(null);
    this.view?.dispose(); this.sim?.dispose();
    for (const t of this._texs || []) t.dispose();
    this._texs = [];
  }

  isReady() {
    if (this.icStage < 0) return true;
    if (this.icStage < 2) return false;
    return !this._needStep();
  }

  // ------------------------------------------------------------------ simulation
  _needStep() {
    const s = this.sim;
    if (!s?.ok || this.icStage < 2) return false;
    const a = this.a;
    if (s.aState === null) return a >= A_PM0;
    return a >= s.aState;
  }

  _advanceSim(maxSteps) {
    const s = this.sim;
    let n = 0;
    // how many steps are due? only the last two need the (expensive) render density field
    let due = 0;
    if (this._needStep()) { let f = s.aState ?? A_PM0; while (f <= this.a && due < 1000) { f += DA; due++; } }
    while (this._needStep() && n < maxSteps) {
      const from = s.aState ?? A_PM0;
      s.step(from, from + DA, due - n <= 2 || n >= maxSteps - 2);
      n++;
    }
    return n;
  }

  _syncSize() {
    const p = this.engine.pipeline;
    if (!p || !this.view) return;
    if (p.width !== this._pw || p.height !== this._ph) {
      this._pw = p.width; this._ph = p.height;
      this.view.setSize(p.width, p.height);
    }
  }

  onResize(w, h) {
    super.onResize(w, h);
    if (this.rigCam) { this.rigCam.aspect = w / h; this.rigCam.updateProjectionMatrix(); }
  }

  update(dt) {
    if (this.disposed) return;
    const e = this.engine;
    this._frame++;
    this._syncSize();
    const input = e.input;

    // ---- cosmic clock
    if (this.icStage >= 1) this.tau += dt;
    const a = this.a = aAt(this.tau);
    const shot = !!e.params.shot;
    if (this.icStage === 2) this._advanceSim(shot || this.tauJumped ? 64 : 3);
    if (this.tauJumped && !this._needStep()) this.tauJumped = false;
    // no PM (unsupported / pm=0): keep a 2LPT render density fresh
    if (this.icStage === 2 && !this.sim.ok && this.sim.floatRT && a >= A_PM0 && Math.abs(a - (this._lptFieldA ?? 0)) > DA * 0.5) {
      this._lptFieldA = a; this.sim.renderField(a);
    }

    // ---- camera
    if (!this.pending) this.rig.handleInput(input, dt);
    this.rig.update(dt);
    const sv = sVis(a);
    const tgt = this.rig._target;
    this.camC.copy(this.rigCam.position).sub(tgt).multiplyScalar(1 / sv).add(tgt);
    this.camera.position.set(0, 0, 0);
    this.camera.quaternion.copy(this.rigCam.quaternion);
    this.camera.updateMatrixWorld(true);
    const fwd = this._fwd.set(0, 0, -1).applyQuaternion(this.camera.quaternion);
    const dC = this.rig._dist / sv;

    // ---- render uniforms
    const U = this.view.U, s = this.sim;
    U.uD1.value = D1(a); U.uD2.value = D2(a); U.uDS.value = subGrowth(a);
    U.uG.value = s.aState !== null && a < s.aState ? Math.max(0, driftTo(a, s.aState)) : 0;
    U.uTime.value += dt;
    const nf = (s.field.a[0] !== null) + (s.field.a[1] !== null);
    U.uFieldOn.value = nf > 0 ? 1 : 0;
    U.tFieldB.value = s.fieldTexB;
    U.tFieldA.value = nf > 1 ? s.fieldTexA : s.fieldTexB;
    const aNew = s.field.a[s.field.cur] ?? 0;
    U.uFieldMix.value = nf > 1 ? Math.min(1, Math.max(0, (a - aNew) / DA)) : 1;
    const camBox = this._v3.copy(this.camC).multiplyScalar(1 / BOX);
    const lead = Math.min(dC, 0.3 * BOX) / BOX;
    const c = this._v3b.copy(camBox).addScaledVector(fwd, lead);
    U.uCamOff.value.copy(c).sub(camBox).multiplyScalar(BOX);
    U.uWrapC.value.set(c.x - Math.floor(c.x), c.y - Math.floor(c.y), c.z - Math.floor(c.z));
    const tanH = Math.tan(this.camera.fov * DEG / 2);
    this.view.accMat.uniforms.uPxScale.value = this.view.accH / (2 * tanH);
    this.view.galMat.uniforms.uPxScale.value = (this._ph || e.height) / (2 * tanH);
    this.view.accMat.uniforms.uFocus.value = dC;
    this.view.galMat.uniforms.uFocus.value = dC;
    this.view.accMat.uniforms.uCoc.value = this.cocK * (this.view.accH / 720);
    // early universe: the fog glows faintly warm until the first structures form
    const cu = this.view.compMat.uniforms;
    cu.uDawn.value = 0.55 * smooth(0.075, 0.03, a);
    this.view.galMat.uniforms.uGalGain.value = 1.0;

    // ---- picking / hover / fly-to
    if (this.icStage === 2) {
      if (this._frame % 12 === 1 || !this.clusterPos) this.view.gather((out) => this._onGather(out), shot);
      this._interact(input, dt);
    }

    // ---- telemetry
    this._teleT -= dt;
    if (this._teleT <= 0 && this.icStage >= 1) {
      this._teleT = 0.2;
      const z = zOfA(a);
      e.ui?.setTelemetry?.({ z: formatZ(Math.max(z, -0.99)), age: formatAge(ageGyr(a)) });
      e.audio?.setParam?.('cosmicGrowth', Math.min(1, D1(a)));
    }
  }

  _onGather(out) {
    if (this.disposed || !this.cl) return;
    const C = this.cl.count;
    this.clusterPos ||= new Float32Array(C * 3);
    for (let k = 0; k < C; k++) { this.clusterPos[k * 3] = out[k * 4]; this.clusterPos[k * 3 + 1] = out[k * 4 + 1]; this.clusterPos[k * 3 + 2] = out[k * 4 + 2]; }
    const nG = this.galGather.length, o = this.galGatherStart;
    this.galPos ||= new Float32Array(nG * 3);
    for (let j = 0; j < nG; j++) { const t = (o + j) * 4; this.galPos[j * 3] = out[t]; this.galPos[j * 3 + 1] = out[t + 1]; this.galPos[j * 3 + 2] = out[t + 2]; }
  }

  /** Box position (periodic) → nearest comoving world image around the camera. */
  _nearestImage(bx, by, bz, out) {
    const cb = this.camC;
    const w = (v, c) => { let d = v - c / BOX; d -= Math.floor(d + 0.5); return c + d * BOX; };
    return out.set(w(bx, cb.x), w(by, cb.y), w(bz, cb.z));
  }

  /** Comoving world → screen px (CSS). Returns false when behind the camera. */
  _toScreen(p, out) {
    const v = this._v3c.copy(p).sub(this.camC).applyMatrix4(this.camera.matrixWorldInverse);
    if (v.z > -0.05) return false;
    v.applyMatrix4(this.camera.projectionMatrix);
    out.x = (v.x * 0.5 + 0.5) * this.engine.width;
    out.y = (-v.y * 0.5 + 0.5) * this.engine.height;
    out.d = -this._v3c.copy(p).sub(this.camC).applyMatrix4(this.camera.matrixWorldInverse).z;
    return true;
  }

  _interact(input, dt) {
    const e = this.engine;
    const ptr = input.pointer;
    const px = (ptr.nx * 0.5 + 0.5) * e.width, py = (-ptr.ny * 0.5 + 0.5) * e.height;
    const tanH = Math.tan(this.camera.fov * DEG / 2), pxs = e.height / (2 * tanH);
    const sc = { x: 0, y: 0, d: 0 };
    const wp = new THREE.Vector3();
    let best = null;
    const canHover = ptr.onCanvas || ptr.clicked;
    if (canHover && !this.pending && this.clusterPos) {
      const d1 = D1(this.a);
      // galaxies first (only meaningful when near enough to see them individually)
      if (this.galPos) {
        const G = this.galGather.length;
        for (let j = 0; j < G; j++) {
          const gi = this.galGather[j];
          if (d1 < this.gal.dign[gi] * 1.3) continue;
          this._nearestImage(this.galPos[j * 3], this.galPos[j * 3 + 1], this.galPos[j * 3 + 2], wp);
          if (!this._toScreen(wp, sc) || sc.d > 45) continue;
          const r = 10 + 4 * Math.sqrt(this.gal.lum[gi]);
          const dd = Math.hypot(sc.x - px, sc.y - py);
          if (dd < r && (!best || dd / r < best.score)) best = { kind: 'galaxy', i: gi, j, x: sc.x, y: sc.y, d: sc.d, r: Math.max(14, r), score: dd / r, pos: wp.clone() };
        }
      }
      if (!best) {
        for (let k = 0; k < this.cl.count; k++) {
          if (d1 < this.cl.dcoll[k] * 0.35) continue;
          this._nearestImage(this.clusterPos[k * 3], this.clusterPos[k * 3 + 1], this.clusterPos[k * 3 + 2], wp);
          if (!this._toScreen(wp, sc) || sc.d > 190 || sc.d < 2) continue;
          const rr = Math.min(70, Math.max(16, (1.2 + this.cl.radius[k]) * pxs / sc.d));
          const dd = Math.hypot(sc.x - px, sc.y - py);
          if (dd < rr * 1.25 && (!best || dd / rr < best.score)) best = { kind: 'cluster', i: k, x: sc.x, y: sc.y, d: sc.d, r: rr, score: dd / rr + sc.d / 400, pos: wp.clone() };
        }
      }
    }
    this.hover = best;

    // click → fly-to, then descend
    if (ptr.clicked && !ptr.dragging && best && !this.pending) {
      let gi;
      if (best.kind === 'galaxy') gi = best.i;
      else gi = this.cl.bcg[best.i] >= 0 ? this.cl.bcg[best.i] : 0;
      const galaxy = this.galIndex[gi] ?? 0;
      const dist = best.kind === 'galaxy' ? 0.35 : Math.max(2.5, 1.5 + this.cl.radius[best.i] * 2);
      this.rig.flyTo(best.pos, dist * sVis(this.a), 2.2);
      this.pending = { galaxy, t: 0, dur: 2.2, name: best.kind === 'galaxy' ? this._galName(gi) : this.clNames[best.i] };
      e.audio?.play?.('whoosh', { gain: 0.6 });
    }
    if (this.pending) {
      this.pending.t += dt;
      if (this.pending.t >= this.pending.dur && !this.pending.fired) {
        this.pending.fired = true;
        e.director.go('galaxy', { galaxy: this.pending.galaxy }, { transition: 'fade' });
      }
    }

    // ring + label
    const ring = this.view.ringMat.uniforms;
    const show = !!(this.hover || this.pending);
    this._ringA += ((show ? 1 : 0) - this._ringA) * Math.min(1, dt * 8);
    ring.uAlpha.value = this._ringA;
    const U = this.view.U;
    if (this.hover) {
      ring.uPos.value.copy(this.hover.pos).sub(this.camC);
      ring.uSize.value = this.hover.r * 2.2;
      ring.uPixelRatio.value = (this._ph || e.height) / e.height;
      this.view.galMat.uniforms.uHover.value = this.hover.kind === 'galaxy' ? this.gal.host[this.hover.i] : -1;
      const label = this.hover.kind === 'galaxy'
        ? this._galName(this.hover.i)
        : `${this.clNames[this.hover.i]} · ${this.clMembers[this.hover.i]} galaxies`;
      e.ui?.setMarkers?.([{ id: 'cw-hover', x: this.hover.x, y: this.hover.y - this.hover.r * 1.15 - 10, visible: true, label, kind: this.hover.kind, distance: this.hover.d }]);
    } else {
      if (!this.pending) ring.uPos.value.set(0, 0, -1e3);
      this.view.galMat.uniforms.uHover.value = -1;
      e.ui?.setMarkers?.(this.pending ? [{ id: 'cw-hover', x: e.width / 2, y: e.height / 2 - 60, visible: true, label: this.pending.name }] : []);
    }
    void U;
  }

  _galName(gi) {
    const idx = this.galIndex?.[gi] ?? 0;
    try { return this.engine.universe.galaxy(idx)?.name ?? `Galaxy ${idx}`; } catch (_) { return `Galaxy ${idx}`; }
  }

  render(pipeline) {
    // shot mode: don't burn software-rendering time on progress frames before the sim is ready
    const skip = this.engine.params.shot && !this.engine.isReady;
    if (this.icStage >= 1 && this.view && !skip) {
      try { this.view.renderAccum(this.camera); } catch (err) { if (!this._warned) { console.error('[cosmic] accum', err); this._warned = true; } }
    }
    this.view.comp.visible = this.icStage >= 1 && !skip;
    if (this.view.galaxies) this.view.galaxies.visible = !skip;
    pipeline.render(this.scene, this.camera);
  }

  /** Debug: percentiles of the accumulated column density (R) and heat fraction. */
  debugStats() {
    const v = this.view, r = this.engine.renderer;
    const w = v.accW, h = v.accH, buf = new Float32Array(w * h * 4);
    this.view.renderAccum(this.camera);
    r.readRenderTargetPixels(v.accum, 0, 0, w, h, buf);
    const R = [], Hh = [];
    for (let i = 0; i < w * h; i += 7) { R.push(buf[i * 4]); Hh.push(buf[i * 4 + 1] / Math.max(1e-6, buf[i * 4])); }
    R.sort((x, y) => x - y); Hh.sort((x, y) => x - y);
    const pc = (A, p) => +A[Math.min(A.length - 1, Math.floor(p * A.length))].toPrecision(3);
    return { R: [0.01, 0.1, 0.5, 0.9, 0.99, 0.999].map((p) => pc(R, p)), heat: [0.5, 0.9, 0.99].map((p) => pc(Hh, p)) };
  }

  getState() {
    const a = this.a;
    return {
      tau: +this.tau.toFixed(2), a: +a.toFixed(4), z: +zOfA(a).toFixed(3), ageGyr: +ageGyr(a).toFixed(3),
      ic: this.icStage, pmSteps: this.sim?.steps ?? 0, pmOK: !!this.sim?.ok,
      particles: this.cfg?.drawCount, galaxies: this.gal?.count ?? 0, clusters: this.cl?.count ?? 0,
      distance: +(this.rig?.distance ?? 0).toFixed(2),
      hover: this.hover ? { kind: this.hover.kind, i: this.hover.i, x: Math.round(this.hover.x), y: Math.round(this.hover.y) } : null,
    };
  }
}

function smooth(e0, e1, x) { const t = Math.min(1, Math.max(0, (x - e0) / (e1 - e0))); return t * t * (3 - 2 * t); }
// drift factor between render time and the state time (∫ da / a³E)
function driftTo(a, aState) { return driftFactor(a, aState); }
