// CosmicMode — the cosmic web, the first thing the player sees. OWNED BY THE COSMIC TRACK.
//
//   Physics   Gaussian random field with an EH98 ΛCDM spectrum (σ8-normalised) generated by a real 3D
//             FFT in a Web Worker (ic.worker.js) → Zel'dovich + 2LPT displacements → GPU particle-mesh
//             gravity with COLA time stepping (sim.js). Comoving box, flat ΛCDM a(t), growth D1/D2.
//   Look      projected column density of 0.26–2.1 M particles with adaptive smoothing, TNG-style
//             temperature colouring, galaxies igniting on their host particles (render.js).
//   Opening   z = 49 fog → sheets → filaments → nodes over ~32 s, then slow future evolution forever;
//             expansion is shown by the comoving camera distance shrinking as a(t) grows.
//
// Units: 1 world unit = 1 comoving Mpc/h. The box is L = 256 Mpc/h, periodic; rendering wraps it around
// the camera so it tiles an infinite universe. Sim time τ (s) → a(τ) via the growth factor.
//
// Contract: clicking/tapping a galaxy or cluster flies to it, then
//   engine.director.go('galaxy', { galaxy: <index> }, { transition: 'fade' })
//
// URL extras (all optional): ct=<sec> start the opening timeline at τ (40 = mature web today),
//   cl=<rank> orbit cluster #rank (0 = most massive), dist=<Mpc/h>, yaw/pitch=<deg>, gal=<rank> frame a galaxy.
import * as THREE from 'three';
import { Mode } from '../../core/Mode.js';
import { OrbitRig } from '../../core/OrbitRig.js';
import { D1, D2, ageGyr, driftFactor, formatAge, formatZ, zOfA } from './cosmology.js';
import { CosmicSim, atlasTiles } from './sim.js';
import { CosmicRenderer } from './render.js';
import { clusterNames } from './names.js';

let BOX = 256;              // Mpc/h (192 on the 64³ lattice: keeps ~3 Mpc/h resolution on phones)
const A_START = 1 / 50;     // z = 49
const T_OPEN = 32;          // s, opening sequence length (z = 49 → 0)
const A_PM0 = 0.05;         // COLA starts at z = 19 (2LPT is exact enough before)
const DA = 0.05;            // PM step in a (19 COLA steps to z = 0)
const DS_SAT = 0.5;         // saturation of the sub-mesh Zel'dovich growth (truncated ZA)
const DEG = Math.PI / 180;

const LN_DS = Math.log(D1(A_START));
function aOfD(D) {
  let lo = Math.log(1e-3), hi = Math.log(3);
  for (let k = 0; k < 40; k++) { const m = 0.5 * (lo + hi); if (D1(Math.exp(m)) < D) lo = m; else hi = m; }
  return Math.exp(0.5 * (lo + hi));
}
/** Scale factor along the opening timeline. Growth is eased so shell crossing (D ≈ 0.3) lands ~12 s in, the web
 * is crisp by ~16 s (z ≈ 1.5) and matures by ~24 s; then it keeps evolving slowly. */
function aAt(tau) {
  if (tau <= 0) return A_START;
  if (tau < T_OPEN) {
    const u = tau / T_OPEN;
    const w = 1 - Math.pow(1 - u, 2.4);
    return aOfD(Math.exp(LN_DS * (1 - w)));
  }
  return 1 + 0.55 * (1 - Math.exp(-(tau - T_OPEN) / 420));   // the future: slow Λ-dominated growth
}
const subGrowth = (a) => { const d = D1(a); return d / Math.sqrt(1 + (d / DS_SAT) * (d / DS_SAT)); };
/** Visual expansion: the comoving camera distance shrinks as (a/1)^0.32 while the opening plays. */
const sVis = (a) => Math.pow(Math.min(a, 1.2), 0.32);

// camera memory across mode switches (returning from a galaxy puts you back where you dove in)
let MEMORY = null;

function h32(x) { x |= 0; x ^= x >>> 16; x = Math.imul(x, 0x7feb352d); x ^= x >>> 15; x = Math.imul(x, 0x846ca68b); x ^= x >>> 16; return x >>> 0; }

export default class CosmicMode extends Mode {
  constructor(engine) {
    super(engine);
    this.inputScheme = 'orbit';
    this.look = {
      exposure: 1.0, tonemap: 'agx-punchy', tonemapHue: 0.7,
      bloom: { strength: 0.5, radius: 0.75, threshold: 0.95, knee: 0.6 },
      vignette: 0.32, grain: 0.012, chromatic: 0.0008, saturation: 1.12, contrast: 1.06, blackPoint: 0.0,
    };
    this.icStage = 0;
    this.tau = 0;
    this.a = A_START;
    this.disposed = false;
    this._v3 = new THREE.Vector3(); this._v3b = new THREE.Vector3(); this._v3c = new THREE.Vector3();
    this._fwd = new THREE.Vector3();
    this.camC = new THREE.Vector3();
    this.clusterPos = null; this.galPos = null;
    this.hover = null;
    this.pending = null;       // fly-to then dive
    this._frame = 0;
    this._teleT = 0;
    this._ringA = 0;
  }

  // ------------------------------------------------------------------ lifecycle
  async enter(params = {}) {
    const e = this.engine;
    const q = e.quality;
    const raw = e.params.raw;
    const tier = q.tier || 'high';
    this.params = params;
    const num = (k) => { const v = raw?.get?.(k); if (v === null || v === undefined || v === '') return undefined; const f = parseFloat(v); return Number.isFinite(f) ? f : undefined; };
    // 128³ lattice ≈ 400 MB of float textures: desktop only; phones and 'low' run 64³ (≈ 50 MB)
    const N = num('n') ?? (tier === 'low' || q.mobile ? 64 : 128);
    const M = num('mesh') ?? N;             // PM mesh = particle lattice (COLA needs force resolution ≥ lattice)
    BOX = N === 64 ? 192 : 256;
    const K = num('k') ?? (N === 64 ? 3 : tier === 'med' ? 2 : tier === 'ultra' ? 4 : 3);
    this.cfg = {
      N, M, K, drawCount: N * N * N,
      // 64³: kernels ~0.93 spacings (smaller ones fall into the Poisson-blotch regime on the coarse lattice)
      h0: (BOX / N) * (N === 64 ? 0.93 : 0.8),
      // big sprites only occur for the few samples near the camera (close-ups): SPH overlap needs room
      maxPx: tier === 'low' ? 24 : tier === 'med' ? 48 : tier === 'ultra' ? 112 : 72,
      accumScale: tier === 'low' ? 0.75 : 1,
      galaxyMax: tier === 'low' ? 9000 : tier === 'med' ? 18000 : tier === 'ultra' ? 48000 : 30000,
    };
    this.startTau = params.returning ? T_OPEN + 6 : (num('ct') ?? params.ct ?? 0);
    this.focusCluster = Math.max(0, Math.floor(num('cl') ?? 0));
    this.focusGalaxy = num('gal');

    // --- GPU sim + renderer
    this.sim = new CosmicSim(e.renderer, { N, M, sub: subGrowth });
    if (num('pm') === 0) this.sim.ok = false;
    this.view = new CosmicRenderer(e, this.sim, { L: BOX, K, drawCount: this.cfg.drawCount, h0: this.cfg.h0, maxPx: this.cfg.maxPx, accumScale: this.cfg.accumScale, fog: 60, sph: num('sph'), kt: num('kt'), aniso: num('an') ?? (N === 64 ? 0 : 1), aspect: num('asp'), em: num('em'), subGain: num('sub'), shellGain: num('shell'),
      veilGain: num('veil'), veilLo: num('vlo') ?? (N === 64 ? 1.2 : undefined), veilHi: num('vhi') ?? (N === 64 ? 4 : undefined), veilSteps: num('vsteps') ?? (tier === 'low' ? 24 : tier === 'med' ? 32 : tier === 'ultra' ? 56 : 40) });
    this.scene.add(this.view.comp);
    // look tuning (URL overrides are for art-direction iteration)
    const cu0 = this.view.compMat.uniforms, au0 = this.view.accMat.uniforms;
    this.sigma0 = cu0.uSigma0.value = num('s0') ?? cu0.uSigma0.value;
    this.toe = num('toe') ?? (N === 64 ? 0.45 : cu0.uToe.value);
    this.bright = num('bright') ?? cu0.uBright.value;
    cu0.uGain.value = num('gain') ?? cu0.uGain.value;
    cu0.uHeatGain.value = num('heat') ?? cu0.uHeatGain.value;
    this.clarity = num('clar') ?? cu0.uClarity.value;
    this.relief = num('relief') ?? cu0.uRelief.value;
    this.gamma = cu0.uGamma.value = num('gamma') ?? cu0.uGamma.value;
    cu0.uShoulder.value = num('shoulder') ?? cu0.uShoulder.value;
    cu0.uAerial.value = num('aerial') ?? cu0.uAerial.value;
    this.em = num('em') ?? this.view.accMat.uniforms.uEm.value;
    this.early = num('early') ?? 0.4;
    this.slab = num('slab') ?? 0.85;
    this.veilLo = this.view.accMat.uniforms.uVeilLo.value; this.veilHi = this.view.accMat.uniforms.uVeilHi.value;
    this.fog = this.view.U.uFog.value = num('fog') ?? this.view.U.uFog.value;
    au0.uH0.value *= num('h0') ?? 1;
    const ru0 = this.view.resolveMat.uniforms;
    ru0.uHeatLo.value = num('hlo') ?? ru0.uHeatLo.value; ru0.uHeatHi.value = num('hhi') ?? ru0.uHeatHi.value;
    this.cocK = num('coc') ?? 1.2;
    this.qBlack = num('qb');                // override: fraction of the screen below the black point
    this.scene.add(this.view.ring);
    this.scene.background = new THREE.Color(0x000000);
    this._syncSize();

    // --- camera: a proxy rig in comoving coordinates; the real camera stays at the origin
    this.camera.fov = fovFor(this.camera.aspect); this.camera.near = 0.01; this.camera.far = 2000; this.camera.updateProjectionMatrix();
    this.rigCam = new THREE.PerspectiveCamera(55, e.aspect, 0.01, 2000);
    const r0 = new OrbitRig(this.rigCam, {
      distance: num('dist') ?? 140 * BOX / 256, minDistance: 1.5, maxDistance: 420,
      yaw: (num('yaw') ?? 38) * DEG, pitch: (num('pitch') ?? 16) * DEG, idleDrift: 0.012, smooth: 4, panSpeed: 0.6,
    });
    this.rig = r0;

    if (params.returning && MEMORY) {
      this.returned = true;
      r0.target.copy(MEMORY.target); r0._target.copy(MEMORY.target);
      r0.yaw = r0._yaw = MEMORY.yaw; r0.pitch = r0._pitch = MEMORY.pitch;
      r0._dist = 3; r0.distance = MEMORY.distance;       // pull back out of the galaxy we left
    }

    // --- initial conditions (worker)
    this._startWorker();

    e.ui?.setLocation?.({ scale: 'Universe', title: 'Cosmic Web', subtitle: `${BOX} Mpc/h · ΛCDM` });
    if (!params.returning) { e.ui?.showTitle?.('REVERENCE', 'a universe, alive', 5200); this._titleT = 6.0; }
    e.ui?.hint?.('drag to orbit · scroll or pinch to zoom · WASD to drift · tap a cluster to descend', 9000);
    e.audio?.setScene?.('cosmic');
  }

  _startWorker() {
    const e = this.engine;
    let w;
    try {
      w = new Worker(new URL('./ic.worker.js', import.meta.url), { type: 'module' });
    } catch (err) {
      console.error('[cosmic] worker failed', err);
      this.icStage = -1; this.ready = true; return;
    }
    this.worker = w;
    const { N, M } = this.cfg;
    const tilesX = atlasTiles(N);
    w.onmessage = (ev) => { try { this._onWorker(ev.data); } catch (err) { console.error('[cosmic] IC upload failed', err); this.icStage = -1; this.ready = true; } };
    w.onerror = (err) => { console.error('[cosmic] IC worker error', err.message || err); this.icStage = -1; this.ready = true; };
    w.postMessage({
      cmd: 'ic', seed: e.universe.seed >>> 0, N, M, box: BOX, tilesX,
      galaxyMax: this.cfg.galaxyMax, formBoost: 2.0, clusterMax: 160, clusterSep: 16, rGlow: 7, rGal: 1.6, rCluster: 5, rEnv: 9,
    });
  }

  _tex(data) {
    const s = this.sim;
    const t = new THREE.DataTexture(data, s.W, s.H, THREE.RGBAFormat, THREE.FloatType);
    t.minFilter = t.magFilter = THREE.NearestFilter; t.generateMipmaps = false; t.needsUpdate = true;
    (this._texs ||= []).push(t);
    return t;
  }

  _onWorker(msg) {
    if (this.disposed) return;
    if (msg.type === 'error') { console.error('[cosmic] IC worker:', msg.error); this.icStage = -1; this.ready = true; return; }
    if (msg.type === 'stage1') {
      this.atlasA = msg.atlasA;
      this.sim.setIC({ psiA: this._tex(msg.atlasA) });
      this.view.U.uSigGlow.value = msg.sigGlow;
      this.icStage = 1;
      if (this.engine.params.debug) console.log(`[cosmic] stage1 ${msg.ms.toFixed(0)} ms`);
    } else if (msg.type === 'stage2') {
      this.atlasB = msg.atlasB;
      this.sim.setIC({ psiB: this._tex(msg.atlasB), psiS: msg.atlasS ? this._tex(msg.atlasS) : null });
      this._setupCatalog(msg.galaxies, msg.clusters);
      this.icStage = 2;
      if (this.engine.params.debug) console.log(`[cosmic] stage2 ${msg.stats.ms.toFixed(0)} ms`, msg.stats, msg.galaxies.count, msg.clusters.count);
      this.worker?.terminate(); this.worker = null;
      // jump along the timeline (URL ct / returning): the sim catches up in update()
      if (this.startTau > 0) { this.tau = this.startTau; this.tauJumped = true; }
      if (!this.returned) this._frameInitialCamera();
    }
  }

  _setupCatalog(gal, cl) {
    const e = this.engine;
    const count = e.universe.cosmic?.galaxyCount ?? 4096;
    this.gal = gal; this.cl = cl;
    // universe galaxy index per catalog entry (catalog is sorted brightest centrals first)
    const G = gal.count;
    this.galIndex = new Int32Array(G);
    const morph = new Float32Array(G);
    for (let i = 0; i < G; i++) {
      const idx = i < count ? i : h32(e.universe.seed * 31 + i) % count;
      this.galIndex[i] = idx;
      const kind = gal.kind[i];
      let m;
      if (i < count) {
        const t = e.universe.galaxy(idx)?.type;
        m = t === 'elliptical' || t === 'lenticular' ? 0 : t === 'irregular' ? 2 : 1;
      } else m = kind === 2 ? ((h32(i) & 3) === 0 ? 2 : 1) : (kind === 1 && (h32(i + 7) & 1) ? 0 : 1);
      morph[i] = m;
    }
    const pts = this.view.setGalaxies(gal, morph);
    this.scene.add(pts);
    this.view.setClusters(cl);
    // cluster membership counts + names
    const members = new Int32Array(cl.count);
    for (let i = 0; i < G; i++) if (gal.cluster[i] >= 0) members[gal.cluster[i]]++;
    this.clMembers = members;
    this.clNames = clusterNames(e.universe.seed, cl.count);
    // gather list: cluster cores, then the brightest galaxies (picking + markers)
    const list = [];
    for (let k = 0; k < cl.count; k++) list.push({ id: cl.center[k], mode: 1 });
    this.galGatherStart = list.length;
    const nG = Math.min(G, 64 * 64 - list.length);
    const byLum = Array.from({ length: G }, (_, i) => i).sort((x, y) => gal.lum[y] - gal.lum[x]).slice(0, nG);
    this.galGather = Int32Array.from(byLum);
    for (const i of byLum) list.push({ id: gal.host[i], mode: 0 });
    this.view.setGatherList(list);
  }

  /** Lagrangian (2LPT, a = 1) estimate of where a lattice particle ends up — used before the GPU gather arrives. */
  _lptPos(id, out) {
    const N = this.cfg.N, tx = atlasTiles(N), W = tx * N;
    const x = id % N, y = Math.floor(id / N) % N, z = Math.floor(id / (N * N));
    const t = ((y + Math.floor(z / tx) * N) * W + x + (z % tx) * N) * 4;
    const A = this.atlasA, B = this.atlasB, d2 = D2(1);
    out.set((x + 0.5) / N, (y + 0.5) / N, (z + 0.5) / N);
    if (A) out.x += A[t], out.y += A[t + 1], out.z += A[t + 2];
    if (B) out.x += d2 * B[t], out.y += d2 * B[t + 1], out.z += d2 * B[t + 2];
    return out;
  }

  _frameInitialCamera() {
    const cl = this.cl;
    let p = new THREE.Vector3(0.5, 0.5, 0.5);
    if (this.focusGalaxy !== undefined && this.gal?.count) {
      const gi = this.galGather?.[Math.min(this.galGather.length - 1, Math.max(0, Math.floor(this.focusGalaxy)))] ?? 0;
      this._lptPos(this.gal.host[gi], p);
      if (this.engine.params.raw?.get?.('dist') == null) this.rig.distance = this.rig._dist = 12;
    } else if (cl?.count) this._lptPos(cl.center[Math.min(cl.count - 1, this.focusCluster)], p);
    p.multiplyScalar(BOX);
    this.rig.target.copy(p); this.rig._target.copy(p);
  }

  exit() {
    this.disposed = true;
    try { this.worker?.terminate(); } catch (_) { /* ignore */ }
    this.engine.ui?.setMarkers?.([]);
    this.engine.ui?.setTelemetry?.(null);
    this.view?.dispose(); this.sim?.dispose();
    for (const t of this._texs || []) t.dispose();
    this._texs = [];
  }

  isReady() {
    if (this.icStage < 0) return true;
    if (this.icStage < 2) return false;
    return !this._needStep();
  }

  // ------------------------------------------------------------------ simulation
  _needStep() {
    const s = this.sim;
    if (!s?.ok || this.icStage < 2) return false;
    const a = this.a;
    if (s.aState === null) return a >= A_PM0;
    return a >= s.aState;
  }

  _advanceSim(maxSteps) {
    const s = this.sim;
    let n = 0;
    // how many steps are due? only the last two need the (expensive) render density field
    let due = 0;
    if (this._needStep()) { let f = s.aState ?? A_PM0; while (f <= this.a && due < 1000) { f += DA; due++; } }
    while (this._needStep() && n < maxSteps) {
      const from = s.aState ?? A_PM0;
      s.step(from, from + DA, due - n <= 2 || n >= maxSteps - 2);
      n++;
    }
    return n;
  }

  _syncSize() {
    const p = this.engine.pipeline;
    if (!p || !this.view) return;
    if (p.width !== this._pw || p.height !== this._ph) {
      this._pw = p.width; this._ph = p.height;
      this.view.setSize(p.width, p.height);
    }
  }

  onResize(w, h) {
    // portrait phones: a wider vertical field keeps the web's horizontal extent (55° → ~68° at 9:19.5)
    this.camera.fov = fovFor(w / Math.max(1, h));
    super.onResize(w, h);
    if (this.rigCam) { this.rigCam.aspect = w / h; this.rigCam.updateProjectionMatrix(); }
  }

  update(dt) {
    if (this.disposed) return;
    const e = this.engine;
    this._frame++;
    this._syncSize();
    const input = e.input;

    // ---- cosmic clock
    if (this.icStage >= 1) this.tau += dt;
    const a = this.a = aAt(this.tau);
    const shot = !!e.params.shot;
    if (this.icStage === 2) this._advanceSim(shot || this.tauJumped ? 64 : 3);
    if (this.tauJumped && !this._needStep()) this.tauJumped = false;
    // no PM (unsupported / pm=0) or before it starts (z > 19): keep a 2LPT render density fresh (veil, colour)
    if (this.icStage === 2 && (!this.sim.ok || a < A_PM0) && this.sim.floatRT && Math.abs(a - (this._lptFieldA ?? 0)) > (a < A_PM0 ? 0.004 : DA * 0.5)) {
      this._lptFieldA = a; this.sim.renderField(a);
    }

    // ---- camera
    if (!this.pending) {
      if (input.axis('look').lengthSq() > 1e-8 || input.zoom || input.axis('move').lengthSq() > 1e-8 || (input.pointer.clicked && !input.pointer.dragging)) this.userMoved = true;
      this.rig.handleInput(input, dt);
      if (this.heroPos && !this.userMoved && !this.returned) this.rig.target.lerp(this.heroPos, 1 - Math.exp(-dt * 0.9));
    }
    this.rig.update(dt);
    const sv = sVis(a);
    const tgt = this.rig._target;
    this.camC.copy(this.rigCam.position).sub(tgt).multiplyScalar(1 / sv).add(tgt);
    this.camera.position.set(0, 0, 0);
    this.camera.quaternion.copy(this.rigCam.quaternion);
    this.camera.updateMatrixWorld(true);
    const fwd = this._fwd.set(0, 0, -1).applyQuaternion(this.camera.quaternion);
    const dC = this.rig._dist / sv;

    // ---- render uniforms
    const U = this.view.U, s = this.sim;
    U.uD1.value = D1(a); U.uD2.value = s.hasB ? D2(a) : 0; U.uDS.value = s.hasS ? subGrowth(a) : 0;
    U.uG.value = s.aState !== null && a < s.aState ? Math.max(0, driftTo(a, s.aState)) : 0;
    U.uTime.value += dt;
    const nf = (s.field.a[0] !== null) + (s.field.a[1] !== null);
    U.uFieldOn.value = nf > 0 ? 1 : 0;
    U.tFieldB.value = s.fieldTexB;
    U.tFieldA.value = nf > 1 ? s.fieldTexA : s.fieldTexB;
    const aNew = s.field.a[s.field.cur] ?? 0;
    U.uFieldMix.value = nf > 1 ? Math.min(1, Math.max(0, (a - aNew) / DA)) : 1;
    const camBox = this._v3.copy(this.camC).multiplyScalar(1 / BOX);
    const lead = Math.min(dC, 0.3 * BOX) / BOX;
    const c = this._v3b.copy(camBox).addScaledVector(fwd, lead);
    U.uCamOff.value.copy(c).sub(camBox).multiplyScalar(BOX);
    U.uWrapC.value.set(c.x - Math.floor(c.x), c.y - Math.floor(c.y), c.z - Math.floor(c.z));
    const tanH = Math.tan(this.camera.fov * DEG / 2);
    this.view.accMat.uniforms.uPxScale.value = this.view.accH / (2 * tanH);
    this.view.accMat.uniforms.uDpr.value = Math.max(0.5, this.view.accH / Math.max(1, e.height));
    this.view.galMat.uniforms.uPxScale.value = (this._ph || e.height) / (2 * tanH);
    const focus = Math.min(dC, 0.42 * BOX);
    this.view.accMat.uniforms.uFocus.value = focus;
    this.view.galMat.uniforms.uFocus.value = focus;
    this.view.accMat.uniforms.uCoc.value = this.cocK * (this.view.accH / 720);
    // early universe: the fog glows faintly warm until the first structures form
    const cu = this.view.compMat.uniforms;
    cu.uDawn.value = 0.6 * smooth(0.07, 0.025, a);
    U.uFog.value = this.fog * (0.45 + 0.55 * smooth(0.1, 0.5, U.uD1.value));
    // young web: a depth slab around the focus (thinner projection = the first wrinkles keep their contrast)
    U.uSlab.value = this.slab * (1 - smooth(0.35, 0.8, U.uD1.value));
    // particle / veil partition: while the web is young its sheets (Zel'dovich pancakes, thinner than the
    // 2 Mpc/h field) are carried by the particles and their Lagrangian sheet tracers; the veil keeps the
    // underdense fog. As halos collapse the partition moves up to the filament threshold.
    const pm = smooth(0.35, 0.8, U.uD1.value), au = this.view.accMat.uniforms;
    au.uVeilLo.value = this.veilLo * (0.3 + 0.7 * pm); au.uVeilHi.value = this.veilHi * (0.3 + 0.7 * pm);
    // exposure follows structure growth: the young, nearly uniform fog is lifted out of the toe, the
    // mature web gets a deep black point so voids read as true OLED black
    const d1 = U.uD1.value;
    const g = smooth(0.08, 0.55, d1);
    const young = Math.min(1, Math.max(0, 1 - d1));
    cu.uBright.value = this.bright * (0.7 + 0.3 * g) * (1 + 0.5 * young);
    cu.uSigma0.value = this.sigma0 * (0.8 + 0.2 * g);
    this._bBase = cu.uBright.value;
    const la = this._lvArgs ||= [0, 0, 0]; la[0] = d1; la[1] = g; la[2] = young;
    this._updateLevels(d1, g, young, dt);
    U.uSeedD.value = 0.6 * (1 - g);
    U.uEarly.value = this.early * (1 - smooth(0.3, 0.75, d1));
    // local contrast and relief sculpt structure as soon as it exists (the young web needs it most: projected
    // through ~200 Mpc/h its contrast is physically low)
    const mature = smooth(0.18, 0.6, d1);
    // emission contrast: steeper (∝ ρ²) while the web is young, so the first wrinkles read as threads
    this.view.accMat.uniforms.uEm.value = this.em + 0.5 * (1 - smooth(0.25, 0.75, d1));
    cu.uClarity.value = this.clarity * mature; cu.uRelief.value = this.relief * mature;
    cu.uNoiseSeed.value = shot ? 0 : (this._frame % 64) * 17.31;
    this.view.veilMat.uniforms.uNoise.value = shot ? 0 : (this._frame % 64) * 13.7;
    U.uSeedMix.value = 1 - smooth(0.1, 0.35, U.uD1.value);
    this.view.galMat.uniforms.uGalGain.value = 1.0;

    // ---- picking / hover / fly-to
    if (this.icStage === 2) {
      if (this._frame % 12 === 1 || !this.clusterPos) this.view.gather((out) => this._onGather(out), shot);
      this._interact(input, dt);
    }

    // ---- telemetry
    this._teleT -= dt;
    if (this._titleT > 0) this._titleT -= dt;
    if (this._teleT <= 0 && this.icStage >= 1) {
      this._teleT = 0.2;
      const z = zOfA(a);
      e.ui?.setTelemetry?.({ z: formatZ(Math.max(z, 0)), age: formatAge(ageGyr(a)) });
      e.audio?.setParam?.('cosmicGrowth', Math.min(1, D1(a)));
    }
  }

  /**
   * Black point / toe width / highlight knee. The toe sits at a measured percentile of the on-screen column
   * density, so voids are true black at every epoch, zoom and quality tier: the primordial fog keeps only
   * its deepest troughs black (faint wrinkles on black), the mature web ~half the screen (voids).
   */
  _updateLevels(d1, g, young, dt, snap = false) {
    const cu = this.view.compMat.uniforms;
    let toe = this.toe * g * (1 - 0.45 * young), w = 1.9, knee = 99, expo = 1;   // fallback (no readback)
    const L = this.levelsSorted;
    if (L) {
      const n = L.length, s0 = cu.uSigma0.value, gain = cu.uGain.value;
      const lq = (q) => Math.log2(1 + Math.max(0, L[Math.min(n - 1, Math.floor(q * (n - 1)))]) / s0) * gain;
      // z ≳ 10: the whole near-uniform fog glows dimly; z ≈ 3: the deepest ~quarter of the troughs are black;
      // today: ~40 % of the screen (the voids)
      const qb = this.qBlack ?? (0.05 + 0.1 * smooth(0.04, 0.3, d1) + 0.29 * smooth(0.3, 0.85, d1) + (this.cfg.N === 64 ? 0.05 : 0));
      toe = lq(qb) - 0.1 * (1 - smooth(0.04, 0.2, d1));
      // toe width follows the measured spread: a young, low-contrast web is stretched over the whole ramp
      w = Math.min(1.9, Math.max(0.4, lq(0.995) - toe));
      // (while young the median must clear the slow start of the toe: mid-tones land ~1/3 up the ramp)
      const wYoung = Math.min(w, Math.max(0.35, (lq(0.5) - toe) * 3.2));
      w += (wYoung - w) * (1 - smooth(0.45, 0.8, d1));
      // highlights: a knee above the brightest ~3 % of the screen, and a highlight exposure that keeps the
      // brightest 0.5 % near 2 (HDR) — a cluster core filling the view keeps its gradient under the bloom
      // highlights: a knee above the brightest ~3 % of the screen (slope 0.35 above it) and an exposure that
      // puts the brightest 0.5 % at ~2.4 before the composite's hue-preserving shoulder
      const G = cu.uGamma.value;
      // close-ups: how much of the frame is bright structure (a cluster core filling the view)?
      const lThr = Math.max(toe + 0.5, (Math.log2(0.6 / Math.max(1e-4, this._bBase)) - 0.35) / G), sThr = s0 * (Math.pow(2, lThr / gain) - 1);
      let lo = 0, hi = n;
      while (lo < hi) { const mid = (lo + hi) >> 1; if (L[mid] <= sThr) lo = mid + 1; else hi = mid; }
      const fBright = this._fBright = (n - lo) / n;
      const wAd = smooth(0.035, 0.12, fBright);
      knee = Math.max(toe + w + 1.0, lq(0.97));
      // ... then the knee drops to the core's outskirts: its whole log-density range is compressed into a
      // visible gradient (white-hot centre, amber body, magenta rim) instead of a plateau on the shoulder
      knee += (Math.max(toe + w + 0.6, lq(0.8)) - knee) * wAd;
      const l995 = lq(0.995), lk = Math.min(l995, knee) + Math.max(0, l995 - knee) * 0.35;
      expo = Math.min(1.5, Math.max(0.02, (2.4 - 1.1 * wAd) / (this._bBase * Math.pow(2, G * lk + 0.35 * wAd))));
      // never let a bad readback (NaN/Inf) reach the shader: fall back to the schedule
      if (!(Number.isFinite(toe) && Number.isFinite(w) && Number.isFinite(knee) && Number.isFinite(expo))) {
        toe = this.toe * g * (1 - 0.45 * young); w = 1.9; knee = 99; expo = 1;
      }
    }
    const lv = this.lev;
    if (!lv || (L && !this._levSnapped) || snap) {
      this.lev = { toe, w, knee, expo };
      if (L) this._levSnapped = true;
    } else {
      const k = 1 - Math.exp(-Math.min(dt, 0.1) * 3);
      lv.toe += (toe - lv.toe) * k; lv.w += (w - lv.w) * k; lv.knee += (knee - lv.knee) * k; lv.expo += (expo - lv.expo) * k;
    }
    cu.uToe.value = this.lev.toe; cu.uToeW.value = this.lev.w; cu.uKnee.value = this.lev.knee;
    cu.uBright.value = this._bBase * this.lev.expo;
  }

  _onGather(out) {
    if (this.disposed || !this.cl) return;
    const C = this.cl.count;
    this.clusterPos ||= new Float32Array(C * 3);
    this.clusterRho ||= new Float32Array(C);
    for (let k = 0; k < C; k++) { this.clusterPos[k * 3] = out[k * 4]; this.clusterPos[k * 3 + 1] = out[k * 4 + 1]; this.clusterPos[k * 3 + 2] = out[k * 4 + 2]; this.clusterRho[k] = out[k * 4 + 3]; }
    this.view.updateClusters(this.clusterPos);
    const nG = this.galGather.length, o = this.galGatherStart;
    this.galPos ||= new Float32Array(nG * 3);
    for (let j = 0; j < nG; j++) { const t = (o + j) * 4; this.galPos[j * 3] = out[t]; this.galPos[j * 3 + 1] = out[t + 1]; this.galPos[j * 3 + 2] = out[t + 2]; }
    // gal=<rank> framing: lock onto the gathered (fully evolved) galaxy position once
    if (this.focusGalaxy !== undefined && !this.galFramed && !this.userMoved && this.galPos) {
      const j = Math.min(nG - 1, Math.max(0, Math.floor(this.focusGalaxy)));
      const p = this._nearestImage(this.galPos[j * 3], this.galPos[j * 3 + 1], this.galPos[j * 3 + 2], new THREE.Vector3());
      this.rig.target.copy(p); this.rig._target.copy(p); this.galFramed = true;
    }
    // rank clusters by their present-day core density (the most massive *final* halos)
    if (this.a > 0.55) {
      const order = Array.from({ length: C }, (_, k) => k).sort((x, y) => this.clusterRho[y] - this.clusterRho[x]);
      this.clusterRank = order;
      if (!this.userMoved && !this.returned && this.focusGalaxy === undefined) {
        const k = order[Math.min(C - 1, this.focusCluster)];
        this.heroPos = this._nearestImage(this.clusterPos[k * 3], this.clusterPos[k * 3 + 1], this.clusterPos[k * 3 + 2], this.heroPos || new THREE.Vector3());
        if (!this.heroSet) { this.heroSet = true; if (this.tau > T_OPEN) { this.rig.target.copy(this.heroPos); this.rig._target.copy(this.heroPos); } }
      }
    }
  }

  /** Box position (periodic) → nearest comoving world image around the camera. */
  _nearestImage(bx, by, bz, out) {
    const cb = this.camC;
    const w = (v, c) => { let d = v - c / BOX; d -= Math.floor(d + 0.5); return c + d * BOX; };
    return out.set(w(bx, cb.x), w(by, cb.y), w(bz, cb.z));
  }

  /** Comoving world → screen px (CSS). Returns false when behind the camera. */
  _toScreen(p, out) {
    const v = this._v3c.copy(p).sub(this.camC).applyMatrix4(this.camera.matrixWorldInverse);
    if (v.z > -0.05) return false;
    v.applyMatrix4(this.camera.projectionMatrix);
    out.x = (v.x * 0.5 + 0.5) * this.engine.width;
    out.y = (-v.y * 0.5 + 0.5) * this.engine.height;
    out.d = -this._v3c.copy(p).sub(this.camC).applyMatrix4(this.camera.matrixWorldInverse).z;
    return true;
  }

  _interact(input, dt) {
    const e = this.engine;
    const ptr = input.pointer;
    const px = (ptr.nx * 0.5 + 0.5) * e.width, py = (-ptr.ny * 0.5 + 0.5) * e.height;
    const tanH = Math.tan(this.camera.fov * DEG / 2), pxs = e.height / (2 * tanH);
    const sc = this._sc ||= { x: 0, y: 0, d: 0 };
    const wp = this._wp ||= new THREE.Vector3();
    let best = null;
    const canHover = ptr.onCanvas || ptr.clicked;
    if (canHover && !this.pending && this.clusterPos) {
      const d1 = D1(this.a);
      // galaxies first (only meaningful when near enough to see them individually)
      if (this.galPos) {
        const G = this.galGather.length;
        for (let j = 0; j < G; j++) {
          const gi = this.galGather[j];
          if (d1 < this.gal.dign[gi] * 1.3) continue;
          this._nearestImage(this.galPos[j * 3], this.galPos[j * 3 + 1], this.galPos[j * 3 + 2], wp);
          if (!this._toScreen(wp, sc) || sc.d > 45) continue;
          const r = 10 + 4 * Math.sqrt(this.gal.lum[gi]);
          const dd = Math.hypot(sc.x - px, sc.y - py);
          if (dd < r && (!best || dd / r < best.score)) best = { kind: 'galaxy', i: gi, j, x: sc.x, y: sc.y, d: sc.d, r: Math.max(14, r), score: dd / r, pos: wp.clone() };
        }
      }
      if (!best) {
        for (let k = 0; k < this.cl.count; k++) {
          if (d1 < this.cl.dcoll[k] * 0.35) continue;
          this._nearestImage(this.clusterPos[k * 3], this.clusterPos[k * 3 + 1], this.clusterPos[k * 3 + 2], wp);
          if (!this._toScreen(wp, sc) || sc.d > 190 || sc.d < 2) continue;
          const rr = Math.min(70, Math.max(16, (1.2 + this.cl.radius[k]) * pxs / sc.d));
          const dd = Math.hypot(sc.x - px, sc.y - py);
          if (dd < rr * 1.25 && (!best || dd / rr < best.score)) best = { kind: 'cluster', i: k, x: sc.x, y: sc.y, d: sc.d, r: rr, score: dd / rr + sc.d / 400, pos: wp.clone() };
        }
      }
    }
    this.hover = best;

    // click → fly-to, then descend
    if (ptr.clicked && !ptr.dragging && best && !this.pending) {
      let gi;
      if (best.kind === 'galaxy') gi = best.i;
      else gi = this.cl.bcg[best.i] >= 0 ? this.cl.bcg[best.i] : 0;
      const galaxy = this.galIndex[gi] ?? 0;
      const dist = best.kind === 'galaxy' ? 0.35 : Math.max(2.5, 1.5 + this.cl.radius[best.i] * 2);
      this.rig.flyTo(best.pos, dist * sVis(this.a), 2.2);
      this.pending = { galaxy, t: 0, dur: 2.2, backDist: best.d * 0.6, name: best.kind === 'galaxy' ? this._galName(gi) : this.clNames[best.i] };
      e.audio?.play?.('whoosh', { gain: 0.6 });
    }
    if (this.pending) {
      this.pending.t += dt;
      if (this.pending.t >= this.pending.dur && !this.pending.fired) {
        this.pending.fired = true;
        MEMORY = { target: this.rig.target.clone(), yaw: this.rig.yaw, pitch: this.rig.pitch, distance: Math.max(20, this.pending.backDist ?? 40) };
        e.director.go('galaxy', { galaxy: this.pending.galaxy }, { transition: 'fade' });
      }
    }

    // ring + label
    const ring = this.view.ringMat.uniforms;
    const show = !!(this.hover || this.pending);
    this._ringA += ((show ? 1 : 0) - this._ringA) * Math.min(1, dt * 8);
    ring.uAlpha.value = this._ringA;
    const U = this.view.U;
    if (this.hover) {
      ring.uPos.value.copy(this.hover.pos).sub(this.camC);
      ring.uSize.value = this.hover.r * 2.2;
      ring.uPixelRatio.value = (this._ph || e.height) / e.height;
      this.view.galMat.uniforms.uHover.value = this.hover.kind === 'galaxy' ? this.gal.host[this.hover.i] : -1;
      const hv = this.hover, dMpc = `${Math.round(hv.d)} Mpc/h`;
      let label, sub;
      if (hv.kind === 'galaxy') {
        label = this._galName(hv.i);
        let type = '';
        try { type = this.engine.universe.galaxy(this.galIndex[hv.i] ?? 0)?.type ?? ''; } catch (_) { /* optional */ }
        sub = type ? `${type} galaxy · ${dMpc}` : dMpc;
      } else {
        label = this.clNames[hv.i];
        sub = `${this.clMembers[hv.i]} galaxies · ${dMpc}`;
      }
      // label above the ring (below it near the top edge); while the title card is up, a label in the central
      // column would crowd it: only the ring shows until the title has faded
      const W = e.width, H = e.height;
      let ly = hv.y - hv.r * 1.15 - 10;
      if (ly < 64) ly = hv.y + hv.r * 1.15 + 30;
      const crowdsTitle = this._titleT > 0 && Math.abs(hv.x - W / 2) < W * 0.3 + 60 && ly > H * 0.12 && ly < H * 0.72;
      e.ui?.setMarkers?.(crowdsTitle ? [] : [{ id: 'cw-hover', x: hv.x, y: ly, visible: true, label, sub, kind: 'cosmic', distance: hv.d }]);
    } else {
      if (!this.pending) ring.uPos.value.set(0, 0, -1e3);
      this.view.galMat.uniforms.uHover.value = -1;
      e.ui?.setMarkers?.(this.pending ? [{ id: 'cw-hover', x: e.width / 2, y: e.height / 2 - 60, visible: true, label: this.pending.name, sub: 'descending', kind: 'cosmic' }] : []);
    }
    void U;
  }

  _galName(gi) {
    const idx = this.galIndex?.[gi] ?? 0;
    try { return this.engine.universe.galaxy(idx)?.name ?? `Galaxy ${idx}`; } catch (_) { return `Galaxy ${idx}`; }
  }

  render(pipeline) {
    // shot mode: don't burn software-rendering time on progress frames before the sim is ready
    const skip = this.engine.params.shot && !this.engine.isReady;
    if (this.icStage >= 1 && this.view && !skip) {
      try {
        this.view.renderAccum(this.camera);
        // (shot mode renders only on demand: measure every rendered frame so captures are deterministic)
        if (this._frame % 15 === 1 || !this.levelsSorted || this.engine.params.shot) this.view.measureLevels((sorted) => { if (!this.disposed) this.levelsSorted = sorted; }, !!this.engine.params.shot);
        // shot mode renders only on demand (advance(N) runs many updates, then one frame): levels measured
        // on an earlier frame are stale by up to N seconds of cosmic time — snap them to this frame's
        if (this.engine.params.shot && this._lvArgs && this.levelsSorted) { const la = this._lvArgs; this._updateLevels(la[0], la[1], la[2], 0, true); }
      } catch (err) { if (!this._warned) { console.error('[cosmic] accum', err); this._warned = true; } }
    }
    this.view.comp.visible = this.icStage >= 1 && !skip;
    if (this.view.galaxies) this.view.galaxies.visible = !skip;
    pipeline.render(this.scene, this.camera);
  }

  /** Test helper: screen position (CSS px) of cluster k (by mass rank), or null if off-screen. */
  screenOfCluster(k = 0) {
    if (!this.clusterPos) return null;
    const wp = this._nearestImage(this.clusterPos[k * 3], this.clusterPos[k * 3 + 1], this.clusterPos[k * 3 + 2], new THREE.Vector3());
    const sc = { x: 0, y: 0, d: 0 };
    return this._toScreen(wp, sc) ? { x: Math.round(sc.x), y: Math.round(sc.y), d: +sc.d.toFixed(1) } : null;
  }
  /** Test helper: the first on-screen cluster rank (most massive first). */
  visibleCluster() {
    for (let k = 0; k < (this.cl?.count ?? 0); k++) {
      const p = this.screenOfCluster(k);
      if (p && p.x > 60 && p.y > 60 && p.x < this.engine.width - 60 && p.y < this.engine.height - 60 && p.d < 170) return { k, ...p };
    }
    return null;
  }
  /** Test helper: park the (mouse) pointer over screen px so hover picking runs in shot mode. */
  hoverAt(x, y) {
    const ptr = this.engine.input.pointer;
    ptr.onCanvas = true; ptr.x = x; ptr.y = y;
    ptr.nx = (x / this.engine.width) * 2 - 1; ptr.ny = -((y / this.engine.height) * 2 - 1);
    return true;
  }

  /** Debug: percentiles of the accumulated column density (R) and heat fraction. */
  debugStats() {
    const v = this.view, r = this.engine.renderer;
    const w = v.accW, h = v.accH, buf = new Float32Array(w * h * 4);
    this.view.renderAccum(this.camera);
    r.readRenderTargetPixels(v.accum, 0, 0, w, h, buf);
    const R = [], Hh = [];
    let bad = 0;
    for (let i = 0; i < w * h; i++) if (!Number.isFinite(buf[i * 4]) || !Number.isFinite(buf[i * 4 + 2])) bad++;
    for (let i = 0; i < w * h; i += 7) { R.push(buf[i * 4]); Hh.push(buf[i * 4 + 1] / Math.max(1e-6, buf[i * 4])); }
    R.sort((x, y) => x - y); Hh.sort((x, y) => x - y);
    const pc = (A, p) => +A[Math.min(A.length - 1, Math.floor(p * A.length))].toPrecision(3);
    const cu = v.compMat.uniforms, P = [0.01, 0.1, 0.3, 0.5, 0.7, 0.9, 0.99, 0.999];
    const lv = (x) => +(Math.log2(1 + x / cu.uSigma0.value) * cu.uGain.value).toFixed(2);
    return {
      D1: +D1(this.a).toFixed(3), nonFinite: bad, R: P.map((p) => pc(R, p)), l: P.map((p) => lv(pc(R, p))), heat: [0.5, 0.9, 0.99].map((p) => pc(Hh, p)),
      toe: +cu.uToe.value.toFixed(3), toeW: +cu.uToeW.value.toFixed(3), knee: +cu.uKnee.value.toFixed(3), sigma0: +cu.uSigma0.value.toFixed(3), bright: +cu.uBright.value.toFixed(4), expo: +(this.lev?.expo ?? 1).toFixed(3), fBright: +(this._fBright ?? 0).toFixed(3),
    };
  }

  getState() {
    const a = this.a;
    return {
      tau: +this.tau.toFixed(2), a: +a.toFixed(4), z: +zOfA(a).toFixed(3), ageGyr: +ageGyr(a).toFixed(3),
      ic: this.icStage, pmSteps: this.sim?.steps ?? 0, pmOK: !!this.sim?.ok,
      particles: this.cfg?.drawCount, galaxies: this.gal?.count ?? 0, clusters: this.cl?.count ?? 0,
      distance: +(this.rig?.distance ?? 0).toFixed(2),
      hover: this.hover ? { kind: this.hover.kind, i: this.hover.i, x: Math.round(this.hover.x), y: Math.round(this.hover.y) } : null,
    };
  }
}

function fovFor(aspect) { return aspect > 0 && aspect < 1 ? Math.min(72, 55 + 25 * (1 - aspect)) : 55; }
function smooth(e0, e1, x) { const t = Math.min(1, Math.max(0, (x - e0) / (e1 - e0))); return t * t * (3 - 2 * t); }
// drift factor between render time and the state time (∫ da / a³E)
function driftTo(a, aState) { return driftFactor(a, aState); }
